---
name: "chatops.ansible_playbook"
action_ref: "st2_pack_aliases.ansible_playbook"
description: "Executes an ansible-playbook"
formats:
  - display: "ansible-playbook </path/to/hosts> </path/to/playbook> <extra-var, extra-var>"
    representation:
      - "ansible-playbook -i {{ hosts }} {{ playbook }} --extra-vars={{ extra_vars }}"
result:
  format: |
    Ansible command `{{ execution.parameters.args }}` result: {~}
    {% if execution.result.stderr %}*Stdout:* {% endif %}
    ```{{ execution.result.stdout }}```
    {% if execution.result.stderr %}*Stderr:* ```{{ execution.result.stderr }}```{% endif %}
extra:
  slack:
    color: "{% if execution.result.succeeded %}good{% else %}danger{% endif %}"
